name: yak_widgets
description: a collection of widgets based on `flutter_hooks` and `riverpod`
version: 0.2.0+0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^2.0.0

dependencies: 
  flutter:
    sdk: flutter
  hooks_riverpod: ^0.13.1
  yak_math: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  stub: ^0.2.0+0
  effective_dart: ^1.3.0

