name: yak_widgets
description: a collection of widgets based on `flutter_hooks` and `riverpod`
version: 0.3.0+0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  stub: ^0.3.0
  effective_dart: ^1.3.0

