name: yak_widgets
description: simply a collection of widgets nothing fancy, but well tested
version: 0.4.0+8
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  flutter:
    sdk: flutter
  yak_result: ^0.1.0
  yak_error_handler: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  stub: ^0.3.0
  effective_dart: ^1.3.2