name: yak_extensions
description: A collection of useful extension for Dart and Flutter
version: 0.1.0+1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter