name: yak_packages
packages:
  - examples/**
  - packages/**

scripts:
  analyze:
    run: |
      melos run analyze:dart --no-select & \
      melos run analyze:flutter --no-select
    description: analyze all packages

  analyze:dart:
    run: |
      melos exec \
      --concurrency 1 \
      -- \
      dart analyze .
    description: Run dart analyze
    select-package:
      flutter: false

  analyze:flutter:
    run: |
      melos exec \
      --concurrency 1 \
      -- \
      flutter analyze .
    description: Run flutter analyze
    select-package:
      flutter: true

  test: 
    run: |
      melos run test:dart --no-select & \
      melos run test:flutter --no-select & \
      melos run test:format
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: |
      melos exec \
      --concurrency 1 \ 
      --fail-fast \
      -- \
      dart test --coverage="coverage"
    description: Run Dart tests for a specific package in this project.
    select-package:
      flutter: false
      dir-exists: test

  test:flutter:
    run: |
      melos exec \
      --concurrency 1 \ 
      --fail-fast \
      -- \
      flutter test --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test

  test:format:
    run: |
      melos exec \
      -- \
      coverage:format_coverage \
      --lcov \
      --check-ignore \
      --out=coverage/lcov.info \
      --report-on=lib
    description: Format all tests' coverage data