name: yak_packages
packages:
  - packages/**

scripts:
  analyze:
    run: |
      melos exec -c 1 -- \
        flutter analyze .
    description: |
      Run `dart analyze` in all packages.
        - Note: you can also rely on your IDEs Dart Analysis / Issues window.
        
  test:
    run: melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:flutter:
    run: melos exec --dir-exists="test" -c 1 --fail-fast -- "flutter test --coverage"
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test
