name: yak_packages
packages:
  - examples/**
  - yak/**
  - yak_error_handler/**
  - yak_math/**
  - yak_runner/**
  - yak_test/**
  - yak_widgets/**
scripts:
  analyze: melos exec -- pub global run tuneup check