name: yak_packages
packages:
  - examples/**
  - packages/**

scripts:
  analyze:
    run: |
      melos exec -c 1 -- \
        flutter analyze .
    description: |
      Run `dart analyze` in all packages.
        - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  test: 
    run: melos run test:dart --no-select &&  melos run test:format --no-select && melos run test:flutter --no-select 
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec -c 1 --fail-fast -- dart test --coverage="coverage"
    description: Run Dart tests for a specific package in this project.
    select-package:
      flutter: false
      dir-exists: test
  
  test:format:
    run: melos exec -c 1 -- format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib --check-ignore
    description: Format Dart tests' coverage data
    select-package:
      flutter: false
      dir-exists: test

  test:flutter:
    run: melos exec -c 1 --fail-fast -- flutter test --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test
