name: stub_example
description: A sample command-line application.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.0.0

dependencies:
  stub: ^2.0.0
  test: ^1.24.2
  
dev_dependencies:
  lints: ^2.1.0

