name: yak_math
description: a collection of flutter classes and extesions part of `yak_packages`
version: 0.1.0+3
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

