name: yak_widgets
description: a collection of classes and extesion part of `yak_packages`
version: 0.1.0+0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: ^1.15.7
  mockito: ^4.1.4
