name: sidebar
description: an example app for the `yak_widgets` `YakSidebar`
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^0.12.2
  flutter_hooks: ^0.15.0
  yak_widgets: ^0.1.1+1
    
flutter:
  uses-material-design: true