name: example
description: A sample command-line application.


environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  riverpod: ^0.12.1
  yak_runner: ^0.2.0+3-hotfix1
  yak_error_handler: ^0.1.0+3-hotfix1

