name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^0.12.1
  yak_runner: ^0.2.0
  yak_error_handler: ^0.1.0
  
dev_dependencies:
  yak_test: ^0.2.0
    
flutter:
  uses-material-design: true