name: byte_token_example
description: A sample command-line application.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  byte_token: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0