name: byte_token_example
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  byte_token: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6