name: byte_token
description: A protobuf based, performant and lightweight token authentication package.
version: 1.0.0+2
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  crypto: ^3.0.2
  fixnum: ^1.0.1
  protobuf: ^2.1.0
  yak_utils: ^1.0.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
