name: yak_runner_example
description: An example for `yak_runner`
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  yak_runner: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
