name: yak_error_handler
description: a simple dart package based on `riverpod` to easily handle `catch`
version: 0.1.0+3-hotfix1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  riverpod: ^0.12.1

dev_dependencies:
  test: ^1.15.7
  mockito: ^4.1.3