name: yak_error_handler
description: a simple dart package that to hadle errors consistently across app and packages                                                                          
version: 0.2.0+1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: ^1.15.7
  effective_dart: ^1.3.0
