name: yak_error_handler
description: a simple dart package based on `riverpod` to easily handle `catch`
version: 0.1.0+3
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  hooks_riverpod: ^0.12.2

dev_dependencies:
  flutter_test: 
