name: yak_error_handler
description: a simple dart package based on `riverpod` to easily handle `catch`
version: 0.2.0+0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: ^1.15.7
