name: stub
description:  a lightweight Dart micro-package to help you stub methods for your tests
version: 0.2.1+2
homepage: https://github.com/iapicca/yak_packages
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  
dev_dependencies:
  test: ^1.16.5
  effective_dart: ^1.3.0
