name: stub
description: a pure `dart` lightweight package to help you stub methods for your tests
version: 1.0.0+4
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  meta: ^1.8.0
  yak_utils: ^1.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
