name: stub
description: a pure `dart` lightweight package to help you stub methods for your tests
version: 0.3.0+3
homepage: https://github.com/iapicca/yak_packages
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  test: ^1.17.10
  effective_dart: ^1.3.2
