name: stub
description: a pure `dart` lightweight package to help you stub methods for your tests
version: 0.3.0+3
homepage: https://github.com/iapicca/yak_packages
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  test: ^1.21.3
  lints: ^2.0.0
