name: yak_runner
description: A Flutter package to make pseudo-TDD and error handling more concise
version: 0.0.3
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies: 
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.9
  mockito: ^4.1.3
  freezed: ^0.12.5