name: yak_runner
description: A Flutter package to make pseudo-TDD and error handling more concise
version: 0.0.2
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies: 
  dartz: ^0.9.1
  equatable: ^1.2.3
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1