name: yak_runner
description: A Flutter package to make pseudo-TDD and error handling more concise

version: 0.0.1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  equatable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1