name: yak_result
description: a lightweight dart micro-package to help you handle functions results 
version: 1.0.0+7
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  meta: ^1.8.0
  yak_utils: ^1.0.1

dev_dependencies:
  lints: ^2.0.1
  stub: ^1.0.0
  test: ^1.22.0
