name: yak_result
description: a lightweight dart micro-package to help you handle functions results 
version: 0.1.0+0
homepage: https://github.com/iapicca/yak_packages
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  meta: ^1.7.0


dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.17.10
  stub: ^0.3.0
