name: yak_result
description: a lightweight dart micro-package to help you handle functions results 
version: 1.0.0+0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  meta: ^1.8.0
  yak_utils: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  stub: ^1.0.0
  test: ^1.21.4
