name: yak_result
description: a lightweight dart micro-package to help you handle functions results 
version: 2.0.0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.1
  yak_utils: ^2.0.0

dev_dependencies:
  lints: ^2.1.0
  stub: ^2.0.0
  test: ^1.24.2
