name: example
description: an example app for `yak_math`
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yak_math: ^0.1.0+0

flutter:
  uses-material-design: true