name: yak
description: a collection of `yak_packages`, all in one place and always up to date
version: 0.2.1+7

homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  yak_test: ^0.2.1
  yak_runner: ^0.2.1
  yak_error_handler: ^0.2.0
  yak_widgets: ^0.1.1
  yak_math: ^0.1.0

dev_dependencies:
  effective_dart: ^1.3.0