name: yak
description: A Flutter package to collect all [Yak] packages
version: 0.0.1+1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  yak_runner: ^0.0.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter