name: yak
description: A collection of all "Yak" packages
version: 0.2.1+3

homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yak_test: ^0.2.0+1-hotfix1 
  yak_runner: ^0.2.0+3-hotfix3
  yak_error_handler: ^0.1.0+3
  yak_widgets: ^0.1.0+2
  yak_math: ^0.1.0+0