name: yak_error_handler
description: a small package to handle exception and errors consistently across app and packages                                                                          
version: 0.3.0+4
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.12.0 <3.0.0'
  
dev_dependencies:
  test: ^1.16.5
  stub: ^0.2.0
  effective_dart: ^1.3.0