name: yak_error_handler
description: a small package to handle exception and errors consistently across app and packages                                                                          
version: 0.4.0+4
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.13.0 <3.0.0'
  
dev_dependencies:
  test: ^1.17.10
  stub: ^0.3.0
  effective_dart: ^1.3.2