name: speedtest
description: a benchmark package for dart
version: 0.1.0+0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:


dev_dependencies:
  test: ^1.17.4
  coverage: ^1.0.2
  stub: ^0.3.0
  effective_dart: ^1.3.0
  yak_test: ^0.5.1