name: yak_utils
description: replicas of flutter `non-null-only` with `const` constructor
version: 0.1.0+0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.17.3
  effective_dart: ^1.3.1
