name: yak_utils
description: a collection of useful functions and extensions` for your projects
version: 1.0.0+4
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
