name: yak_utils
description: a collection of useful functions and extensions` for your projects
version: 0.1.0+1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.17.3
  effective_dart: ^1.3.1
