name: yak_utils
description: a collection of useful functions and extensions` for your projects
version: 2.0.0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.1

dev_dependencies:
  mocktail: ^0.3.0
  lints: ^2.1.0
  test: ^1.24.2
  stub: ^2.0.0
  yak_test: ^2.0.0