name: yak_utils
description: a collection of useful functions and extensions` for your projects
version: 1.0.1+2
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.18.5 <3.0.0'
  
dependencies:
  meta: ^1.8.0

dev_dependencies:
  mocktail: ^0.3.0
  lints: ^2.0.1
  test: ^1.22.0
  stub: ^1.0.0
  yak_test: ^1.0.1