name: yak_flutter
description: A collection of tools and extensions for Flutter.
version: 1.0.1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  yak_tween: ^0.1.0
  yak_runner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  stub: ^1.0.0