name: yak_math
description: replicas of flutter `non-null-only` with `const` constructor
version: 0.2.0+0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^2.0.0


dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

