name: yak_runner
description: A Dart package that makes running functions safer and easier to test
version: 0.3.0+1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yak_error_handler: ^0.3.0
  
dev_dependencies:
  test: ^1.16.5
  stub: ^0.2.0
  effective_dart: ^1.3.0
