name: yak_runner
description: A Dart package that makes running functions safer and easier to test
version: 1.0.0+1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  meta: ^1.7.0
  yak_result: ^1.0.0
  yak_utils: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  stub: ^1.0.0
  test: ^1.21.4
