name: yak_runner
description: A Dart package that makes running functions safer and easier to test
version: 0.5.0+2
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  meta: ^1.8.0
  yak_result: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  stub: ^0.3.0
  test: ^1.21.3
