name: yak_runner
description: A Dart package that makes running functions safer and easier to test
version: 0.4.1+0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  yak_error_handler: ^0.4.1
  
dev_dependencies:
  test: ^1.17.10
  stub: ^0.3.0
  effective_dart: ^1.3.2
