name: yak_test
description: a Dart package that helps to testing apps made with `yak_packages`
version: 0.2.2+1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  meta: ^1.2.4
  mockito: ^4.1.3
  test: ^1.15.7
  yak_runner: ^0.2.2

dev_dependencies:
  effective_dart: ^1.3.0