name: yak_test
description: a Dart package that helps to testing apps made with `yak_packages`
version: 1.0.1+1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  meta: ^1.8.0
  yak_runner: ^1.0.1
  stub: ^1.0.0
  test: ^1.22.0

dev_dependencies:
  mocktail: ^0.3.0
  lints: ^2.0.1


