name: yak_test
description: a Dart package that helps to testing apps made with `yak_packages`
version: 1.0.0+2
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  meta: ^1.8.0
  yak_runner: ^1.0.0
  stub: ^1.0.0
  test: ^1.21.6

dev_dependencies:
  lints: ^2.0.0

