name: yak_test
description: a Dart package that helps to testing apps made with `yak_packages`
version: 0.5.2+0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  meta: ^1.8.0
  yak_result: ^0.1.0
  yak_runner: ^0.5.0
  stub: ^0.3.0
  test: ^1.21.3

dev_dependencies:
  lints: ^2.0.0

