name: yak_test
description: a Dart package that helps to testing apps made with `yak_packages`
version: 0.4.0+1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  test: ^1.17.0
  stub: ^0.3.0
  yak_runner: ^0.4.0
  yak_error_handler: ^0.4.0


dev_dependencies:
  effective_dart: ^1.3.1