name: yak_test
description: A Dart package to help testing when using `yak_packages`
version: 0.2.1+0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies: 
  meta: ^1.2.4
  mockito: ^4.1.3
  test: ^1.15.7
  yak_runner: ^0.2.1
  yak_error_handler: ^0.1.1
  riverpod: ^0.12.2