name: yak_test
description: A Flutter package to help testing when using `yak_packages`
version: 0.1.0+6
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies: 
  meta: ^1.2.4
  mockito: ^4.1.3
  yak_runner: ^0.1.0+6-hotfix3
  flutter_test:
    sdk: flutter