name: 'pub-lish'
on:
  push:
    branches:
      - master
jobs:
  pub-lish:
    name: 'publish to pub.dev'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
      - name: 'setup flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: 'update PATH'
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH && \
          echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV  
      - name: 'setup credentials'
        run: |
          mkdir $HOME/.pub-cache/ && \
          touch $HOME/.pub-cache/credentials.json && \
          cat <<EOF > $HOME/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
            "expiration":${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
          }
          EOF
      - name: 'install dependencies'
        uses: bluefireteam/melos-action@v1 
      - name: 'publishing'
        run: |
          yes | melos run publish