name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  flutter_test:
    name: run flutter_test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt-openj9'
          java-version: '9'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Add pub cache bin to PATH
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Add pub cache to PATH
        run: |
          echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV
      - name: Activate `melos` 
        run: |
          dart pub global activate melos
      - name: Install dependencies
        run: melos bootstrap
      - name: Run tests
        run: melos run test
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: packages/*/coverage/lcov.info