name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  flutter_test:
    name: run flutter_test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt-openj9'
          java-version: '9'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV
      - name: Activate `coverage` 
        run: dart pub global activate coverage
      - name: Activate `melos` 
        run: dart pub global activate melos
      - name: Install dependencies
        run: melos bootstrap
      - name: Analyze
        run: melos exec --ignore="marvel" -- "flutter analyze"
      - name: Run tests
        run: melos run test
      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash | bash   