name: yak_tween
description: A replica of flutter Tween that allows `const` constructor and accepts/returns only NN
version: 0.1.0+4
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  yak_utils: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.2

