name: yak_tween
description: A replica of flutter Tween that allows `const` constructor and accepts/returns only NN
version: 0.1.0+9
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=3.0.5'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2
  yak_utils: ^1.0.0

dependency_overrides:
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1