name: yak_tween
description: A replica of flutter Tween that allows `const` constructor and accepts/returns only NN.
version: 0.1.0+14
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  yak_utils: ^1.0.1

dev_dependencies:
  test: ^1.22.0
  flutter_lints: ^2.0.1