name: yak_tween
description: A replica of flutter Tween that allows `const` constructor and accepts/returns only NN.
version: 2.0.0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  yak_utils: ^2.0.0

dev_dependencies:
  test: ^1.24.2
  flutter_lints: ^2.0.1