name: yak_tween
description: A replica of flutter Tween that allows `const` constructor and accepts/returns only NN.
version: 0.1.0+11
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2
  yak_utils: ^1.0.0

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.1