name: yak_tween
description: A new Flutter package project.
version: 0.1.0+1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  yak_utils: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1

